export type Language = "en" | "ar";
import { embeddedImages } from "./embeddedImageAssets";
import { embeddedVideos } from "./embeddedVideoAssets";
import { embeddedPricingImage } from "./embeddedPricingImage";

export const BRAND_NAME = "PPFStudio";

export const WHATSAPP_NUMBER = "966537358631";
export const WHATSAPP_DISPLAY = "+966 53 735 8631";
export const INSTAGRAM_URL = "https://www.instagram.com/ppf_studio_com?igsi=Nmh6b3BmNGRrZ3oz";
export const SNAPCHAT_URL = "https://www.snapchat.com/add/jkjabed2026?share_id=lKZ1ASIv4Jk&locale=en-US";
export const TIKTOK_URL = "https://www.tiktok.com/@ppf_studio?_r=1&_t=ZS-99ECEM4AyhB";
export const WHATSAPP_MESSAGES: Record<Language, string> = {
  ar: "مرحباً، أرغب في الاستفسار عن خدمة حماية الطلاء PPF والحصول على عرض سعر وحجز موعد.",
  en: "Hello, I am interested in your PPF service. I would like to get a quote and book an appointment.",
};

export function whatsappHref(language: Language) {
  return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(WHATSAPP_MESSAGES[language])}`;
}

const externalImages = {
  hero: "/manus-storage/obsidian-hero_414be125_b0fbd711.webp",
  galleryCoupe: "/manus-storage/ppf-studio-black-car_54ef85c6.jpg",
  detailSuv: "/manus-storage/ppf-installation-detail_d528883e.jpg",
  installation: "/manus-storage/ppf-studio-black-car_54ef85c6.jpg",
  mark: "/manus-storage/ppf-logo-user-640_a0ea4ecd.webp",
  secondaryDetail: "/manus-storage/ppf-installation-detail_d528883e.jpg",
  secondaryStudio: "/manus-storage/ppf-studio-black-car_54ef85c6.jpg",
  preserveEnglish: "/manus-storage/ppf-preserve-en_a8652e9f_feae942a.webp",
  preserveArabic: "/manus-storage/ppf-preserve-ar_ae6423a7_788a8321.webp",
  definitionEnglish: "/manus-storage/ppf-definition-en_ccdaafe2_337ba0e1.webp",
  definitionArabic: "/manus-storage/ppf-definition-ar_ff569d7f_6d307d08.webp",
  beforeAfterRollsEnglish: "/manus-storage/ppf-before-after-rolls-en_9f002695_3a2f327e.webp",
  beforeAfterRollsArabic: "/manus-storage/ppf-before-after-rolls-ar_39628be9_cd827487.webp",
  premiumProtectionEnglish: "/manus-storage/ppf-premium-protection-en_71f2cef3_4fa50155.webp",
  premiumProtectionArabic: "/manus-storage/ppf-premium-protection-ar_b59e9cda_491c8521.webp",
  beforeProtectionAfterEnglish: "/manus-storage/ppf-before-protection-after-en_fef2eab0_ae1abfe4.webp",
  beforeProtectionAfterArabic: "/manus-storage/ppf-before-protection-after-ar_d6d869c9_5093d086.webp",
  scratchCostEnglish: "/manus-storage/ppf-scratch-cost-en_6103e150_21515aea.webp",
  scratchCostArabic: "/manus-storage/ppf-scratch-cost-ar_ff3ce699_de39f90a.webp",
} as const;

export const USE_EMBEDDED_IMAGES = true;
type ImageMap = Record<keyof typeof externalImages | "pricingArabic", string>;

export const images: ImageMap = USE_EMBEDDED_IMAGES
  ? {
      ...externalImages,
      ...embeddedImages,
      installation: embeddedImages.galleryCoupe,
      secondaryDetail: embeddedImages.detailSuv,
      secondaryStudio: embeddedImages.galleryCoupe,
      pricingArabic: embeddedPricingImage,
    }
  : { ...externalImages, pricingArabic: "" };
export const externalImageFallbacks = externalImages;

export const translations = {
  en: {
    locale: "en-US",
    dir: "ltr" as const,
    languageName: "English",
    languageShort: "EN",
    modalTitle: "Welcome",
    modalBody: "Choose your preferred language to continue.",
    modalArabic: "العربية",
    modalArabicHint: "متابعة باللغة العربية",
    modalEnglish: "English",
    modalEnglishHint: "Continue in English",
    nav: [
      ["Home", "home"],
      ["Services", "services"],
      ["Our Work", "work"],
      ["Process", "process"],
      ["Why Us", "why-us"],
      ["About", "about"],
      ["Contact", "contact"],
    ],
    navCta: "WhatsApp",
    heroEyebrow: "PPFSTUDIO / AUTOMOTIVE PROTECTION ATELIER",
    heroTitle: "Protect your paint. Preserve its beauty.",
    heroBody: "Advanced paint protection using premium PPF films, professionally installed to protect your vehicle while preserving its original appearance.",
    viewWork: "View our work",
    book: "Book an appointment",
    heroWhatsapp: "Chat with us on WhatsApp",
    scroll: "Scroll to explore",
    servicesEyebrow: "01 / THE CRAFT",
    servicesTitle: "Protection, refined.",
    servicesBody: "Every installation is built around the vehicle in front of us: its lines, its finish, and the way it will be driven.",
    servicesHeading: "Our services",
    services: [
      ["PPF Paint Protection", "Advanced protection against scratches, stone chips and everyday road damage.", "01"],
      ["Complete Vehicle Protection", "Full-body coverage using premium-quality PPF film and measured installation.", "02"],
      ["Front-End Protection", "Shield the bumper, hood, fenders and mirrors from the road ahead.", "03"],
      ["Ceramic Coating", "A deep gloss finish with advanced hydrophobic performance and easier maintenance.", "04"],
      ["Headlight Protection", "Keep the clarity and finish of your headlights protected from daily wear.", "05"],
      ["Custom PPF", "Protection packages designed around your vehicle, your priorities and your finish.", "06"],
    ],
    workEyebrow: "02 / SELECTED WORK",
    workTitle: "The finish is the proof.",
    workBody: "Explore a selection of recent protection projects, from full-body coverage to precise front-end work.",
    filters: ["All", "Full Body PPF", "Front PPF", "Luxury Cars", "SUV", "Before & After", "Installation"],
    galleryLabels: ["Full Body PPF", "Luxury Cars", "SUV", "Installation", "Before & After", "Front PPF", "Protection Guide", "PPF Explained", "Paint Correction", "Premium Protection", "Protection Journey", "Scratch Cost", "Pricing Guide"],
    beforeEyebrow: "03 / THE DIFFERENCE",
    beforeTitle: "Before & after",
    beforeBody: "Drag across the finish to see how invisible protection keeps the original surface looking untouched.",
    beforeLabel: "Before",
    afterLabel: "After",
    videoEyebrow: "04 / IN THE ATELIER",
    videoTitle: "See our work in action.",
    videoBody: "A closer look at the measured, meticulous process behind every installation.",
    videoCategories: ["PPF Installation", "Before & After", "Vehicle Reveal", "Final Result"],
    processEyebrow: "05 / A MEASURED PROCESS",
    processTitle: "Nothing is rushed.",
    processBody: "Six considered steps. One uncompromising result.",
    process: [
      ["Vehicle Inspection", "We assess the paint, panels and priorities before a single cut is made."],
      ["Surface Preparation", "A meticulous clean creates the ideal surface for film adhesion."],
      ["Film Installation", "Each panel is aligned, wrapped and settled with a trained eye."],
      ["Edge Finishing", "Edges are refined for a clean finish that disappears into the bodywork."],
      ["Final Inspection", "Every surface is checked under controlled light before handover."],
      ["Vehicle Delivery", "Your vehicle returns protected, finished and ready for the road."],
    ],
    qualityEyebrow: "06 / MATERIAL INTELLIGENCE",
    qualityTitle: "Protection you can see. Quality you can trust.",
    qualityBody: "The best protection is measured in the details you do not notice: clarity, fit, finish and the confidence to drive.",
    qualityFeatures: ["High optical clarity", "Scratch resistance", "Stone chip protection", "UV resistance", "Hydrophobic surface", "Easy maintenance", "Long-lasting protection"],
    stats: [["FILM", "Premium-grade PPF materials"], ["EDGE", "Refined panel finishing"], ["LIGHT", "Controlled inspection"], ["CARE", "Considered handover"]],
    testimonialsEyebrow: "07 / CLIENT NOTES",
    testimonialsTitle: "What our customers say",
    reviewCountLabel: "approved client reviews",
    reviewOpen: "Read client reviews",
    reviewEmpty: "No approved reviews yet. Be the first to share your experience.",
    reviewFormTitle: "Share your experience",
    reviewFormName: "Your name",
    reviewFormVehicle: "Vehicle (optional)",
    reviewFormRating: "Rating",
    reviewFormText: "Your review",
    reviewFormSubmit: "Submit for review",
    reviewPending: "Saved successfully. Your review is awaiting approval before publication.",
    reviewModeratedNote: "Reviews are saved immediately and published after a quick authenticity check.",
    reviewTrackTitle: "Track your review",
    reviewTrackBody: "Enter your private reference code to check the current status.",
    reviewReferenceLabel: "Reference code",
    reviewReferencePlaceholder: "PPF-XXXXXXXXXXXX",
    reviewTrackSubmit: "Check status",
    reviewTrackLoading: "Checking status...",
    reviewTrackNotFound: "No review was found for that reference code.",
    reviewReferenceInvalid: "Enter a valid reference in the format PPF-XXXXXXXXXXXX.",
    reviewStatusPending: "Pending approval",
    reviewStatusApproved: "Approved and published",
    reviewStatusRejected: "Not approved",
    reviewTrackDate: "Submitted",
    reviewReferenceCopy: "Copy reference",
    reviewReferenceCopied: "Reference copied",

    reviewModerationTitle: "Review moderation",
    reviewApprove: "Approve",
    reviewReject: "Reject",
    reviewAdminEmpty: "No reviews are waiting for moderation.",
    ctaTitle: "Ready to protect your vehicle?",
    ctaBody: "Contact us today for a consultation, quotation or appointment.",
    ctaButton: "Chat with us on WhatsApp",
    contactEyebrow: "08 / START A CONVERSATION",
    contactTitle: "Bring the finish you want to keep.",
    contactBody: "Tell us about your vehicle and we will recommend a protection plan built around it.",
    contactLabel: "WhatsApp",
    footerDescription: "Professional automotive protection for the finish worth keeping.",
    footerLinks: "Explore",
    footerContact: "Contact",
    footerCopyright: "© 2026 PPFStudio. All rights reserved.",
    floatingWhatsapp: "Chat with us on WhatsApp",
    close: "Close",
    previous: "Previous image",
    next: "Next image",
    openImage: "Open image",
    playVideo: "Play video",
    menu: "Open menu",
    closeMenu: "Close menu",
    error: "Something went wrong. Please try again.",
  },
  ar: {
    locale: "ar-SA",
    dir: "rtl" as const,
    languageName: "العربية",
    languageShort: "AR",
    modalTitle: "مرحباً بك",
    modalBody: "اختر لغتك المفضلة للمتابعة",
    modalArabic: "العربية",
    modalArabicHint: "متابعة باللغة العربية",
    modalEnglish: "English",
    modalEnglishHint: "Continue in English",
    nav: [
      ["الرئيسية", "home"],
      ["خدماتنا", "services"],
      ["أعمالنا", "work"],
      ["خطوات العمل", "process"],
      ["لماذا نحن", "why-us"],
      ["من نحن", "about"],
      ["تواصل معنا", "contact"],
    ],
    navCta: "واتساب",
    heroEyebrow: "PPFSTUDIO / استوديو حماية السيارات",
    heroTitle: "احمِ جمال سيارتك. وحافظ على قيمتها.",
    heroBody: "حماية متقدمة للطلاء باستخدام أفلام حماية عالية الجودة، مع تركيب احترافي يمنح سيارتك حماية ومظهراً استثنائياً.",
    viewWork: "شاهد أعمالنا",
    book: "احجز موعدك",
    heroWhatsapp: "تواصل معنا عبر واتساب",
    scroll: "اكتشف المزيد",
    servicesEyebrow: "01 / الحرفية",
    servicesTitle: "حماية بمستوى مختلف.",
    servicesBody: "كل عملية تركيب تبدأ من السيارة أمامنا: خطوطها، طلاءها، والطريقة التي ستقود بها.",
    servicesHeading: "خدماتنا",
    services: [
      ["حماية الطلاء PPF", "حماية متقدمة من الخدوش والحصى والعوامل اليومية.", "01"],
      ["حماية كاملة للسيارة", "تغطية شاملة باستخدام أفلام حماية عالية الجودة وتركيب دقيق.", "02"],
      ["حماية الواجهة الأمامية", "حماية الصدام والكبوت والرفارف والمرايا من أضرار الطريق.", "03"],
      ["الطلاء الخزفي", "لمعان عميق مع خصائص طاردة للماء وسهولة أكبر في العناية.", "04"],
      ["حماية المصابيح", "الحفاظ على وضوح ولمعان المصابيح محمياً من العوامل اليومية.", "05"],
      ["PPF مخصص", "باقات حماية مصممة حول سيارتك وأولوياتك ومظهرها.", "06"],
    ],
    workEyebrow: "02 / أعمال مختارة",
    workTitle: "النتيجة هي الدليل.",
    workBody: "استكشف مجموعة من مشاريع حماية السيارات، من التغطية الكاملة إلى حماية الواجهة الأمامية بدقة.",
    filters: ["الكل", "PPF كامل", "الواجهة الأمامية", "سيارات فاخرة", "SUV", "قبل وبعد", "تركيب"],
    galleryLabels: ["PPF كامل", "سيارات فاخرة", "SUV", "تركيب", "قبل وبعد", "الواجهة الأمامية", "دليل الحماية", "ما هو PPF؟", "تصحيح الطلاء", "حماية فاخرة", "رحلة الحماية", "تكلفة الخدش", "دليل الأسعار"],
    beforeEyebrow: "03 / الفرق الواضح",
    beforeTitle: "قبل وبعد",
    beforeBody: "اسحب عبر السطح لترى كيف تحافظ الحماية غير المرئية على مظهر الطلاء الأصلي.",
    beforeLabel: "قبل",
    afterLabel: "بعد",
    videoEyebrow: "04 / داخل الاستوديو",
    videoTitle: "شاهد عملية العمل.",
    videoBody: "نظرة أقرب على العملية الدقيقة والمتأنية خلف كل تركيب.",
    videoCategories: ["تركيب PPF", "قبل وبعد", "كشف السيارة", "النتيجة النهائية"],
    processEyebrow: "05 / خطوات مدروسة",
    processTitle: "لا شيء يتم على عجل.",
    processBody: "ست خطوات مدروسة. نتيجة واحدة لا تقبل التنازل.",
    process: [
      ["فحص السيارة", "نقيّم الطلاء والألواح والأولويات قبل إجراء أي قص."],
      ["تجهيز السطح", "تنظيف دقيق يهيئ السطح المثالي لالتصاق الفيلم."],
      ["تركيب الفيلم", "تتم محاذاة كل لوحة وتغليفها وتثبيتها بعين خبيرة."],
      ["تشطيب الحواف", "نصقل الحواف للحصول على نتيجة نظيفة تندمج مع هيكل السيارة."],
      ["الفحص النهائي", "يتم فحص كل سطح تحت إضاءة دقيقة قبل التسليم."],
      ["تسليم السيارة", "تعود سيارتك محمية ومكتملة وجاهزة للطريق."],
    ],
    qualityEyebrow: "06 / ذكاء المواد",
    qualityTitle: "حماية يمكنك رؤيتها. جودة يمكنك الوثوق بها.",
    qualityBody: "أفضل حماية تظهر في التفاصيل التي لا تلاحظها: الوضوح، الملاءمة، التشطيب والثقة أثناء القيادة.",
    qualityFeatures: ["وضوح بصري عالٍ", "مقاومة الخدوش", "حماية من الحصى", "مقاومة الأشعة فوق البنفسجية", "سطح طارد للماء", "سهولة التنظيف", "حماية طويلة الأمد"],
    stats: [["فيلم", "أفلام حماية عالية الجودة"], ["حواف", "تشطيب دقيق للحواف"], ["ضوء", "فحص تحت إضاءة مضبوطة"], ["عناية", "تسليم باهتمام كامل"]],
    testimonialsEyebrow: "07 / آراء العملاء",
    testimonialsTitle: "ماذا يقول عملاؤنا",
    reviewCountLabel: "مراجعات عملاء معتمدة",
    reviewOpen: "قراءة مراجعات العملاء",
    reviewEmpty: "لا توجد مراجعات معتمدة بعد. كن أول من يشارك تجربته.",
    reviewFormTitle: "شارك تجربتك",
    reviewFormName: "اسمك",
    reviewFormVehicle: "السيارة (اختياري)",
    reviewFormRating: "التقييم",
    reviewFormText: "مراجعتك",
    reviewFormSubmit: "إرسال للمراجعة",
    reviewPending: "تم حفظ مراجعتك بنجاح، وهي بانتظار الموافقة قبل نشرها.",
    reviewModeratedNote: "يتم حفظ المراجعات فوراً ونشرها بعد التحقق السريع من أصالتها.",
    reviewTrackTitle: "تتبع مراجعتك",
    reviewTrackBody: "أدخل رمزك المرجعي الخاص لمعرفة الحالة الحالية.",
    reviewReferenceLabel: "الرمز المرجعي",
    reviewReferencePlaceholder: "PPF-XXXXXXXXXXXX",
    reviewTrackSubmit: "التحقق من الحالة",
    reviewTrackLoading: "جارٍ التحقق من الحالة...",
    reviewTrackNotFound: "لم يتم العثور على مراجعة بهذا الرمز المرجعي.",
    reviewReferenceInvalid: "أدخل رمزاً مرجعياً صحيحاً بالصيغة PPF-XXXXXXXXXXXX.",
    reviewStatusPending: "بانتظار الموافقة",
    reviewStatusApproved: "تمت الموافقة والنشر",
    reviewStatusRejected: "لم تتم الموافقة",
    reviewTrackDate: "تاريخ الإرسال",
    reviewReferenceCopy: "نسخ الرمز المرجعي",
    reviewReferenceCopied: "تم نسخ الرمز المرجعي",

    reviewModerationTitle: "مراجعة آراء العملاء",
    reviewApprove: "موافقة",
    reviewReject: "رفض",
    reviewAdminEmpty: "لا توجد مراجعات بانتظار المراجعة.",
    ctaTitle: "هل أنت مستعد لحماية سيارتك؟",
    ctaBody: "تواصل معنا اليوم للحصول على استشارة وعرض سعر وحجز موعد.",
    ctaButton: "تواصل معنا عبر واتساب",
    contactEyebrow: "08 / ابدأ محادثة",
    contactTitle: "حافظ على المظهر الذي تحبه.",
    contactBody: "أخبرنا عن سيارتك وسنقترح خطة حماية مصممة حولها.",
    contactLabel: "واتساب",
    footerDescription: "حماية احترافية للسيارات التي تستحق الحفاظ على مظهرها.",
    footerLinks: "استكشف",
    footerContact: "تواصل معنا",
    footerCopyright: "© 2026 PPFStudio. جميع الحقوق محفوظة.",
    floatingWhatsapp: "تواصل معنا عبر واتساب",
    close: "إغلاق",
    previous: "الصورة السابقة",
    next: "الصورة التالية",
    openImage: "فتح الصورة",
    playVideo: "تشغيل الفيديو",
    menu: "فتح القائمة",
    closeMenu: "إغلاق القائمة",
    error: "حدث خطأ، يرجى المحاولة مرة أخرى.",
  },
} as const;

export type Content = (typeof translations)[Language];

export const galleryItems = [
  { id: 1, category: "Full Body PPF", src: images.galleryCoupe, alt: "Pearl coupe with full-body paint protection film" },
  { id: 2, category: "Luxury Cars", src: images.secondaryDetail, alt: "Luxury vehicle paint surface under studio light" },
  { id: 3, category: "SUV", src: images.detailSuv, alt: "SUV headlight and PPF edge detail" },
  { id: 4, category: "Installation", src: images.installation, alt: "Technician aligning clear PPF on a vehicle hood" },
  { id: 5, category: "Before & After", src: images.secondaryStudio, alt: "Glossy vehicle panel in a premium studio" },
  { id: 6, category: "Front PPF", src: images.hero, alt: "Front quarter of a protected black sports coupe" },
  { id: 7, category: "Before & After", src: images.preserveEnglish, arSrc: images.preserveArabic, alt: "Three-panel comparison showing a new car, worn paint without PPF, and protected paint with PPF", arAlt: "مقارنة من ثلاث لوحات توضح السيارة الجديدة والطلاء المتضرر بدون PPF والطلاء المحمي مع PPF" },
  { id: 8, category: "Installation", src: images.definitionEnglish, arSrc: images.definitionArabic, alt: "PPF definition over a red luxury car during film installation", arAlt: "شرح معنى PPF فوق سيارة فاخرة حمراء أثناء تركيب الفيلم" },
  { id: 9, category: "Before & After", src: images.beforeAfterRollsEnglish, arSrc: images.beforeAfterRollsArabic, alt: "Before and after comparison of visible paint imperfections and professional PPF installation", arAlt: "مقارنة قبل وبعد بين عيوب الطلاء الظاهرة وتركيب PPF الاحترافي" },
  { id: 10, category: "Full Body PPF", src: images.premiumProtectionEnglish, arSrc: images.premiumProtectionArabic, alt: "Premium car protected inside a transparent protective dome", arAlt: "سيارة فاخرة محمية داخل قبة حماية شفافة" },
  { id: 11, category: "Installation", src: images.beforeProtectionAfterEnglish, arSrc: images.beforeProtectionAfterArabic, alt: "Four-panel journey from pristine paint through road risks and professional PPF installation to a protected glossy finish", arAlt: "رحلة من أربع لوحات تبدأ بطلاء أصلي مروراً بمخاطر الطريق وتركيب PPF الاحترافي وتنتهي بلمعان محمي" },
  { id: 12, category: "Before & After", src: images.scratchCostEnglish, arSrc: images.scratchCostArabic, alt: "Infographic explaining the real repair cost of a scratch and how PPF safeguards a car investment", arAlt: "رسم توضيحي يشرح التكلفة الحقيقية لإصلاح الخدش وكيف يحمي PPF استثمار السيارة" },
  { id: 13, category: "Installation", src: images.pricingArabic, arSrc: images.pricingArabic, alt: "Arabic PPFStudio pricing and protection packages", arAlt: "قائمة أسعار وباقات حماية PPFStudio باللغة العربية" },
] as const;

export const videoItems = [
  { title: "PPF Installation", src: images.installation, videoSrc: embeddedVideos.ppfInstallation, isEmbedded: true },
  { title: "Before & After", src: images.detailSuv },
  { title: "Vehicle Reveal", src: images.galleryCoupe },
  { title: "Final Result", src: images.hero },
] as const;
